### ISSUE TITLE
Logging in to FAS3 Doesnt work

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fas#148]
On my Test instance, i try to log into a user, and get the following error:

```
AttributeError

AttributeError: 'GroupMembership' object has no attribute 'group'

Traceback (most recent call last)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] result = handler(request)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] response = handler(request)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] reraise(*exc_info)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] response = handler(request)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] view_name

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] response = view_callable(context, request)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/config/views.py", line 353, in rendered_view

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] result = view(context, request)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/config/views.py", line 483, in _class_requestonly_view

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] response = getattr(inst, attr)()

    File "/home/rlerch/Source/fas/fas/views/home.py", line 76, in login

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] result = process_login(self.request, person, password)

    File "/home/rlerch/Source/fas/fas/security.py", line 291, in process_login

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] notify(LoginSucceeded(request, person))

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/registry.py", line 91, in notify

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] [ _ for _ in self.subscribers(events, None) ]

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/zope/interface/registry.py", line 328, in subscribers

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] return self.adapters.subscribers(objects, provided)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/zope/interface/adapter.py", line 596, in subscribers

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] subscription(*objects)

    File "/home/rlerch/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/config/adapters.py", line 103, in derived_subscriber

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] return subscriber(arg[0])

    File "/home/rlerch/Source/fas/fas/subscribers/people.py", line 108, in check_ssh_key

     [Display the sourcecode for this frame]  [Open an interactive python shell in this frame] if m.group and m.group.requires_ssh:

AttributeError: 'GroupMembership' object has no attribute 'group'
```

**Comment by pypingou** [comment]
@ryanlerch could you check now? Should be fixed I think

**Comment by skrzepto** [comment]
This is working for me
