### ISSUE TITLE
[FAS3] Trouble loading the project now locally

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#214]
I wanted to load up fas3 on my local machine but it keeps throwing 

```
TypeError: Note must be text (unicode)
```

Specifics:

I'm running this hooked to a postgres server but this also threw the same error on sqlite

-------
Dump:

```
Serving on http://0.0.0.0:6543
2016-11-19 00:24:02,162 ERROR [waitress:11674][pyramid_debugtoolbar:toolbar][toolbar_tween:233] Exception at http://0.0.0.0:6543/
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=b87eee303814eda328aa&tb=140019938846608
Traceback (most recent call last):
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 85, in tm_tween
    t.note(native_(request.path_info, 'utf-8'))
  File "/home/skrzepto/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/transaction/_transaction.py", line 537, in note
    raise TypeError("Note must be text (unicode)")
TypeError: Note must be text (unicode)
2016-11-19 00:24:02,211 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1140] select version()
2016-11-19 00:24:02,211 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1143] {}
2016-11-19 00:24:02,212 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1140] select current_schema()
2016-11-19 00:24:02,213 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1143] {}
2016-11-19 00:24:02,213 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_cursor_execute:1235] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2016-11-19 00:24:02,213 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_cursor_execute:1236] {}
2016-11-19 00:24:02,214 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_cursor_execute:1235] SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2016-11-19 00:24:02,214 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_cursor_execute:1236] {}
2016-11-19 00:24:02,215 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1140] show standard_conforming_strings
2016-11-19 00:24:02,215 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1143] {}
2016-11-19 00:24:02,215 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_begin_impl:679] BEGIN (implicit)
2016-11-19 00:24:02,219 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1140] SELECT anon_1.people_id AS anon_1_people_id, anon_1.people_username AS anon_1_people_username, anon_1.people_password AS anon_1_people_password, anon_1.people_fullname AS anon_1_people_fullname, anon_1.people_ircnick AS anon_1_people_ircnick, anon_1.people_avatar AS anon_1_people_avatar, anon_1.people_avatar_id AS anon_1_people_avatar_id, anon_1.people_introduction AS anon_1_people_introduction, anon_1.people_postal_address AS anon_1_people_postal_address, anon_1.people_country_code AS anon_1_people_country_code, anon_1.people_locale AS anon_1_people_locale, anon_1.people_birthday AS anon_1_people_birthday, anon_1.people_birthday_month AS anon_1_people_birthday_month, anon_1.people_telephone AS anon_1_people_telephone, anon_1.people_facsimile AS anon_1_people_facsimile, anon_1.people_affiliation AS anon_1_people_affiliation, anon_1.people_bio AS anon_1_people_bio, anon_1.people_timezone AS anon_1_people_timezone, anon_1.people_gpg_fingerprint AS anon_1_people_gpg_fingerprint, anon_1.people_ssh_key AS anon_1_people_ssh_key, anon_1.people_email AS anon_1_people_email, anon_1.people_recovery_email AS anon_1_people_recovery_email, anon_1.people_bugzilla_email AS anon_1_people_bugzilla_email, anon_1.people_email_token AS anon_1_people_email_token, anon_1.people_unverified_email AS anon_1_people_unverified_email, anon_1.people_security_question AS anon_1_people_security_question, anon_1.people_security_answer AS anon_1_people_security_answer, anon_1.people_login_attempt AS anon_1_people_login_attempt, anon_1.people_password_token AS anon_1_people_password_token, anon_1.people_old_password AS anon_1_people_old_password, anon_1.people_certificate_serial AS anon_1_people_certificate_serial, anon_1.people_status AS anon_1_people_status, anon_1.people_status_timestamp AS anon_1_people_status_timestamp, anon_1.people_privacy AS anon_1_people_privacy, anon_1.people_email_alias AS anon_1_people_email_alias, anon_1.people_blog_rss AS anon_1_people_blog_rss, anon_1.people_latitude AS anon_1_people_latitude, anon_1.people_longitude AS anon_1_people_longitude, anon_1.people_fas_token AS anon_1_people_fas_token, anon_1.people_github_token AS anon_1_people_github_token, anon_1.people_twitter_token AS anon_1_people_twitter_token, anon_1.people_login_timestamp AS anon_1_people_login_timestamp, anon_1.people_creation_timestamp AS anon_1_people_creation_timestamp, anon_1.people_update_timestamp AS anon_1_people_update_timestamp, signed_license_agreement_1.id AS signed_license_agreement_1_id, signed_license_agreement_1.license_id AS signed_license_agreement_1_license_id, signed_license_agreement_1.person_id AS signed_license_agreement_1_person_id 
FROM (SELECT people.id AS people_id, people.username AS people_username, people.password AS people_password, people.fullname AS people_fullname, people.ircnick AS people_ircnick, people.avatar AS people_avatar, people.avatar_id AS people_avatar_id, people.introduction AS people_introduction, people.postal_address AS people_postal_address, people.country_code AS people_country_code, people.locale AS people_locale, people.birthday AS people_birthday, people.birthday_month AS people_birthday_month, people.telephone AS people_telephone, people.facsimile AS people_facsimile, people.affiliation AS people_affiliation, people.bio AS people_bio, people.timezone AS people_timezone, people.gpg_fingerprint AS people_gpg_fingerprint, people.ssh_key AS people_ssh_key, people.email AS people_email, people.recovery_email AS people_recovery_email, people.bugzilla_email AS people_bugzilla_email, people.email_token AS people_email_token, people.unverified_email AS people_unverified_email, people.security_question AS people_security_question, people.security_answer AS people_security_answer, people.login_attempt AS people_login_attempt, people.password_token AS people_password_token, people.old_password AS people_old_password, people.certificate_serial AS people_certificate_serial, people.status AS people_status, people.status_timestamp AS people_status_timestamp, people.privacy AS people_privacy, people.email_alias AS people_email_alias, people.blog_rss AS people_blog_rss, people.latitude AS people_latitude, people.longitude AS people_longitude, people.fas_token AS people_fas_token, people.github_token AS people_github_token, people.twitter_token AS people_twitter_token, people.login_timestamp AS people_login_timestamp, people.creation_timestamp AS people_creation_timestamp, people.update_timestamp AS people_update_timestamp 
FROM people 
WHERE people.username IS NULL 
 LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN signed_license_agreement AS signed_license_agreement_1 ON anon_1.people_id = signed_license_agreement_1.person_id
2016-11-19 00:24:02,219 INFO  [waitress:11674][sqlalchemy.engine.base.Engine:base][_execute_context:1143] {'param_1': 1}


```

**Comment by skrzepto** [comment]
Looks like its not a FAS problem but a pyramid library problem. More info can be found here
https://github.com/Pylons/pyramid_tm/issues/49

**Comment by skrzepto** [comment]
Make sure `pyramid-tm>=1.0.2`
